# Generated by Django 4.2.7 on 2023-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('singer', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('audio', models.FileField(upload_to=None)),
            ],
        ),
    ]
