# Generated by Django 4.2.7 on 2023-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
